<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Staging_Test_Suite_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2b2ce35c-440b-4690-b4e0-9b808ebc0279</testSuiteGuid>
   <testCaseLink>
      <guid>8f7566b4-cf88-4ae0-9083-253f101b079a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Login_Functionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b3483fa-6b0e-40e2-9157-cfa54d88799b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eae95191-9ad2-4462-8e25-52b4ce1176e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Admin_Login_Partner_Creation_and_Delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc9e7f63-368d-4009-bda4-40efda1aabbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06a8fc6d-3c3b-47dc-a2e1-575d3ef1239f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b662de43-eea6-4668-8f89-d2e31fc44ddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Admin_Login_Partner_Creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acb34ed6-25ea-49ce-bdea-d0bae581529f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0748c0d6-6dce-4a86-bb92-3e8e81d2a700</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>568f05ed-3655-4b69-b304-f709adb57bbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Garage_Management_Add_New_Garage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>50aa22b2-949d-46c2-beb3-0084a86e6880</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Promotion_Creation_FLow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e824eb7c-85cc-4d98-9cdf-a65bbc32805b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Transient Flow_Partner_Parking_Payments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c49f4d-a868-4d20-96b4-5dfdda7de3a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445703ed-d5a9-4b8b-8c2d-46fe84969462</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e8adf17-374e-419b-b571-87d9feaaffe7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New_Staging_Env/Transient Flow_Multi_Partner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3271ae8-4a5b-4853-8053-fcffae779ee7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a30e1e0f-8b0c-4beb-85bc-a5e44fce540a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
